### ISSUE TITLE
name collision

### ISSUE THREAD

**Issue by willghatch** [rash-sh/rash#140]
FYI, there is already a shell called Rash: https://rash-lang.org

Granted, they are really only similar in that they are both described as being a “shell” language.  But for what it's worth, it might cause some confusion.

**Comment by pando85** [comment]
Yep, I understand the problem. Anyway, this is an oriented container tool and yours seems a cool interactive shell.

I think is not a big issue and the solutions that I see are worst than the problem itself, at least from my point of view.

What do you propose to solve this?

**Comment by willghatch** [comment]
It seems like your Rash is only about a month old, so I thought it would likely be new enough that a name change would be relatively cheap and perhaps worth doing.  If you don't think so, don't worry about it.

**Comment by pando85** [comment]
Thanks for your comprehension.
