### ISSUE TITLE
tags

### ISSUE THREAD

**Issue by pando85** [rash-sh/rash#223]

**Comment by pando85** [comment]
After implemented docopt, is this still necessary?

**Comment by theowenyoung** [comment]
are there some features like tags or roles? My case need some collections to custom specific rashs

**Comment by pando85** [comment]
Right now I'm using specific entrypoints/scripts for different functionality. E.g.: https://git.grigri.cloud/agil/desktop-installer/src/commit/661cbb3c0b52e5fe00b886d82af5e30a86164300

So I will close this, as it is unnecessary at this stage.
