### ISSUE TITLE
[BUG] template module can not found {{ env.OSTYPE }}

### ISSUE THREAD

**Issue by theowenyoung** [rash-sh/rash#259]
**Describe the bug**

when template contains `{{ env.OSTYPE }}`

```bash
[ERROR] Failed to render '/Users/green/env/dot_path'
error - Custom { kind: InvalidData, error: Error { kind: Msg("Failed to render '/Users/green/env/dot_path'"), source: Some(Error { kind: Msg("Variable `env.OSTYPE` not found in context while rendering '/Users/green/env/dot_path'"), source: None }) } }
```
**To Reproduce**

main.yml:

```yaml
template:
  src: test.txt
  dest: ~/test.txt
```

test.txt:

```
{{ env.OSTYPE }}
```

`rash ./main.yml`

**Additional context**

```
{{rash.path}}
```

is fine.

**Comment by theowenyoung** [comment]
oh my fault, `$OSTYPE` is not an env variable, but how to check current OS name, I want to use it as the condition. I use rash as my dotfiles manager.

**Comment by pando85** [comment]
It could be interesting to have some facts or variables that could be loaded optionally as Ansible do.
